# Generated by Django 5.1.4 on 2026-09-06 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantité')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat")),
                ('date', models.DateField(verbose_name='Date')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Enregistrée le')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='products.product', verbose_name='Produit')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='suppliers.supplier', verbose_name='Fournisseur')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Entrée de stock',
                'verbose_name_plural': 'Entrées de stock',
                'db_table': 'stock_entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantité')),
                ('reason', models.CharField(choices=[('damage', 'Produit endommagé'), ('loss', 'Perte'), ('internal_use', 'Usage interne'), ('correction', "Correction d'inventaire"), ('other', 'Autre')], default='other', max_length=20, verbose_name='Motif')),
                ('date', models.DateField(verbose_name='Date')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Enregistrée le')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_outputs', to='products.product', verbose_name='Produit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Sortie de stock',
                'verbose_name_plural': 'Sorties de stock',
                'db_table': 'stock_outputs',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
